/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PilotLaunchRouteImport } from './routes/pilot-launch'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppStudentProgressRouteImport } from './routes/app.student.progress'
import { Route as AppStudentHomeRouteImport } from './routes/app.student.home'
import { Route as AppStudentFeedbackRouteImport } from './routes/app.student.feedback'
import { Route as AppLeaderStandardsRouteImport } from './routes/app.leader.standards'
import { Route as AppLeaderOverviewRouteImport } from './routes/app.leader.overview'
import { Route as AppLeaderInterventionsRouteImport } from './routes/app.leader.interventions'
import { Route as AppDistrictOverviewRouteImport } from './routes/app.district.overview'
import { Route as AppDistrictImplementationRouteImport } from './routes/app.district.implementation'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as AppStudentAssignmentsIndexRouteImport } from './routes/app.student.assignments.index'
import { Route as AppStudentAssignmentsExpressionsCheckpointRouteImport } from './routes/app.student.assignments.expressions-checkpoint'
import { Route as AppCoursesCourseSlugRosterRouteImport } from './routes/app.courses.$courseSlug.roster'
import { Route as AppCoursesCourseSlugPassbackRouteImport } from './routes/app.courses.$courseSlug.passback'
import { Route as AppCoursesCourseSlugOverviewRouteImport } from './routes/app.courses.$courseSlug.overview'
import { Route as AppCoursesCourseSlugInterventionsRouteImport } from './routes/app.courses.$courseSlug.interventions'
import { Route as AppCoursesCourseSlugInsightsRouteImport } from './routes/app.courses.$courseSlug.insights'
import { Route as AppCoursesCourseSlugGradebookRouteImport } from './routes/app.courses.$courseSlug.gradebook'
import { Route as AppCoursesCourseSlugAssignmentsIndexRouteImport } from './routes/app.courses.$courseSlug.assignments.index'
import { Route as AppCoursesCourseSlugStudentsStudentSlugRouteImport } from './routes/app.courses.$courseSlug.students.$studentSlug'
import { Route as AppCoursesCourseSlugAssignmentsAssignmentSlugRouteImport } from './routes/app.courses.$courseSlug.assignments.$assignmentSlug'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotLaunchRoute = PilotLaunchRouteImport.update({
  id: '/pilot-launch',
  path: '/pilot-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentProgressRoute = AppStudentProgressRouteImport.update({
  id: '/student/progress',
  path: '/student/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentHomeRoute = AppStudentHomeRouteImport.update({
  id: '/student/home',
  path: '/student/home',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentFeedbackRoute = AppStudentFeedbackRouteImport.update({
  id: '/student/feedback',
  path: '/student/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderStandardsRoute = AppLeaderStandardsRouteImport.update({
  id: '/leader/standards',
  path: '/leader/standards',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderOverviewRoute = AppLeaderOverviewRouteImport.update({
  id: '/leader/overview',
  path: '/leader/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLeaderInterventionsRoute = AppLeaderInterventionsRouteImport.update({
  id: '/leader/interventions',
  path: '/leader/interventions',
  getParentRoute: () => AppRoute,
} as any)
const AppDistrictOverviewRoute = AppDistrictOverviewRouteImport.update({
  id: '/district/overview',
  path: '/district/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppDistrictImplementationRoute =
  AppDistrictImplementationRouteImport.update({
    id: '/district/implementation',
    path: '/district/implementation',
    getParentRoute: () => AppRoute,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppStudentAssignmentsIndexRoute =
  AppStudentAssignmentsIndexRouteImport.update({
    id: '/student/assignments/',
    path: '/student/assignments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentAssignmentsExpressionsCheckpointRoute =
  AppStudentAssignmentsExpressionsCheckpointRouteImport.update({
    id: '/student/assignments/expressions-checkpoint',
    path: '/student/assignments/expressions-checkpoint',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugRosterRoute =
  AppCoursesCourseSlugRosterRouteImport.update({
    id: '/courses/$courseSlug/roster',
    path: '/courses/$courseSlug/roster',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugPassbackRoute =
  AppCoursesCourseSlugPassbackRouteImport.update({
    id: '/courses/$courseSlug/passback',
    path: '/courses/$courseSlug/passback',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugOverviewRoute =
  AppCoursesCourseSlugOverviewRouteImport.update({
    id: '/courses/$courseSlug/overview',
    path: '/courses/$courseSlug/overview',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugInterventionsRoute =
  AppCoursesCourseSlugInterventionsRouteImport.update({
    id: '/courses/$courseSlug/interventions',
    path: '/courses/$courseSlug/interventions',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugInsightsRoute =
  AppCoursesCourseSlugInsightsRouteImport.update({
    id: '/courses/$courseSlug/insights',
    path: '/courses/$courseSlug/insights',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugGradebookRoute =
  AppCoursesCourseSlugGradebookRouteImport.update({
    id: '/courses/$courseSlug/gradebook',
    path: '/courses/$courseSlug/gradebook',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugAssignmentsIndexRoute =
  AppCoursesCourseSlugAssignmentsIndexRouteImport.update({
    id: '/courses/$courseSlug/assignments/',
    path: '/courses/$courseSlug/assignments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugStudentsStudentSlugRoute =
  AppCoursesCourseSlugStudentsStudentSlugRouteImport.update({
    id: '/courses/$courseSlug/students/$studentSlug',
    path: '/courses/$courseSlug/students/$studentSlug',
    getParentRoute: () => AppRoute,
  } as any)
const AppCoursesCourseSlugAssignmentsAssignmentSlugRoute =
  AppCoursesCourseSlugAssignmentsAssignmentSlugRouteImport.update({
    id: '/courses/$courseSlug/assignments/$assignmentSlug',
    path: '/courses/$courseSlug/assignments/$assignmentSlug',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/pilot-launch': typeof PilotLaunchRoute
  '/product': typeof ProductRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/thank-you': typeof ThankYouRoute
  '/app/activity': typeof AppActivityRoute
  '/app/': typeof AppIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/app/district/implementation': typeof AppDistrictImplementationRoute
  '/app/district/overview': typeof AppDistrictOverviewRoute
  '/app/leader/interventions': typeof AppLeaderInterventionsRoute
  '/app/leader/overview': typeof AppLeaderOverviewRoute
  '/app/leader/standards': typeof AppLeaderStandardsRoute
  '/app/student/feedback': typeof AppStudentFeedbackRoute
  '/app/student/home': typeof AppStudentHomeRoute
  '/app/student/progress': typeof AppStudentProgressRoute
  '/app/courses/$courseSlug/gradebook': typeof AppCoursesCourseSlugGradebookRoute
  '/app/courses/$courseSlug/insights': typeof AppCoursesCourseSlugInsightsRoute
  '/app/courses/$courseSlug/interventions': typeof AppCoursesCourseSlugInterventionsRoute
  '/app/courses/$courseSlug/overview': typeof AppCoursesCourseSlugOverviewRoute
  '/app/courses/$courseSlug/passback': typeof AppCoursesCourseSlugPassbackRoute
  '/app/courses/$courseSlug/roster': typeof AppCoursesCourseSlugRosterRoute
  '/app/student/assignments/expressions-checkpoint': typeof AppStudentAssignmentsExpressionsCheckpointRoute
  '/app/student/assignments/': typeof AppStudentAssignmentsIndexRoute
  '/app/courses/$courseSlug/assignments/$assignmentSlug': typeof AppCoursesCourseSlugAssignmentsAssignmentSlugRoute
  '/app/courses/$courseSlug/students/$studentSlug': typeof AppCoursesCourseSlugStudentsStudentSlugRoute
  '/app/courses/$courseSlug/assignments/': typeof AppCoursesCourseSlugAssignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/pilot-launch': typeof PilotLaunchRoute
  '/product': typeof ProductRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/thank-you': typeof ThankYouRoute
  '/app/activity': typeof AppActivityRoute
  '/app': typeof AppIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/app/district/implementation': typeof AppDistrictImplementationRoute
  '/app/district/overview': typeof AppDistrictOverviewRoute
  '/app/leader/interventions': typeof AppLeaderInterventionsRoute
  '/app/leader/overview': typeof AppLeaderOverviewRoute
  '/app/leader/standards': typeof AppLeaderStandardsRoute
  '/app/student/feedback': typeof AppStudentFeedbackRoute
  '/app/student/home': typeof AppStudentHomeRoute
  '/app/student/progress': typeof AppStudentProgressRoute
  '/app/courses/$courseSlug/gradebook': typeof AppCoursesCourseSlugGradebookRoute
  '/app/courses/$courseSlug/insights': typeof AppCoursesCourseSlugInsightsRoute
  '/app/courses/$courseSlug/interventions': typeof AppCoursesCourseSlugInterventionsRoute
  '/app/courses/$courseSlug/overview': typeof AppCoursesCourseSlugOverviewRoute
  '/app/courses/$courseSlug/passback': typeof AppCoursesCourseSlugPassbackRoute
  '/app/courses/$courseSlug/roster': typeof AppCoursesCourseSlugRosterRoute
  '/app/student/assignments/expressions-checkpoint': typeof AppStudentAssignmentsExpressionsCheckpointRoute
  '/app/student/assignments': typeof AppStudentAssignmentsIndexRoute
  '/app/courses/$courseSlug/assignments/$assignmentSlug': typeof AppCoursesCourseSlugAssignmentsAssignmentSlugRoute
  '/app/courses/$courseSlug/students/$studentSlug': typeof AppCoursesCourseSlugStudentsStudentSlugRoute
  '/app/courses/$courseSlug/assignments': typeof AppCoursesCourseSlugAssignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/launch': typeof LaunchRoute
  '/pilot-launch': typeof PilotLaunchRoute
  '/product': typeof ProductRoute
  '/research': typeof ResearchRoute
  '/security': typeof SecurityRoute
  '/thank-you': typeof ThankYouRoute
  '/app/activity': typeof AppActivityRoute
  '/app/': typeof AppIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/app/district/implementation': typeof AppDistrictImplementationRoute
  '/app/district/overview': typeof AppDistrictOverviewRoute
  '/app/leader/interventions': typeof AppLeaderInterventionsRoute
  '/app/leader/overview': typeof AppLeaderOverviewRoute
  '/app/leader/standards': typeof AppLeaderStandardsRoute
  '/app/student/feedback': typeof AppStudentFeedbackRoute
  '/app/student/home': typeof AppStudentHomeRoute
  '/app/student/progress': typeof AppStudentProgressRoute
  '/app/courses/$courseSlug/gradebook': typeof AppCoursesCourseSlugGradebookRoute
  '/app/courses/$courseSlug/insights': typeof AppCoursesCourseSlugInsightsRoute
  '/app/courses/$courseSlug/interventions': typeof AppCoursesCourseSlugInterventionsRoute
  '/app/courses/$courseSlug/overview': typeof AppCoursesCourseSlugOverviewRoute
  '/app/courses/$courseSlug/passback': typeof AppCoursesCourseSlugPassbackRoute
  '/app/courses/$courseSlug/roster': typeof AppCoursesCourseSlugRosterRoute
  '/app/student/assignments/expressions-checkpoint': typeof AppStudentAssignmentsExpressionsCheckpointRoute
  '/app/student/assignments/': typeof AppStudentAssignmentsIndexRoute
  '/app/courses/$courseSlug/assignments/$assignmentSlug': typeof AppCoursesCourseSlugAssignmentsAssignmentSlugRoute
  '/app/courses/$courseSlug/students/$studentSlug': typeof AppCoursesCourseSlugStudentsStudentSlugRoute
  '/app/courses/$courseSlug/assignments/': typeof AppCoursesCourseSlugAssignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/launch'
    | '/pilot-launch'
    | '/product'
    | '/research'
    | '/security'
    | '/thank-you'
    | '/app/activity'
    | '/app/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/app/district/implementation'
    | '/app/district/overview'
    | '/app/leader/interventions'
    | '/app/leader/overview'
    | '/app/leader/standards'
    | '/app/student/feedback'
    | '/app/student/home'
    | '/app/student/progress'
    | '/app/courses/$courseSlug/gradebook'
    | '/app/courses/$courseSlug/insights'
    | '/app/courses/$courseSlug/interventions'
    | '/app/courses/$courseSlug/overview'
    | '/app/courses/$courseSlug/passback'
    | '/app/courses/$courseSlug/roster'
    | '/app/student/assignments/expressions-checkpoint'
    | '/app/student/assignments/'
    | '/app/courses/$courseSlug/assignments/$assignmentSlug'
    | '/app/courses/$courseSlug/students/$studentSlug'
    | '/app/courses/$courseSlug/assignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/launch'
    | '/pilot-launch'
    | '/product'
    | '/research'
    | '/security'
    | '/thank-you'
    | '/app/activity'
    | '/app'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/app/district/implementation'
    | '/app/district/overview'
    | '/app/leader/interventions'
    | '/app/leader/overview'
    | '/app/leader/standards'
    | '/app/student/feedback'
    | '/app/student/home'
    | '/app/student/progress'
    | '/app/courses/$courseSlug/gradebook'
    | '/app/courses/$courseSlug/insights'
    | '/app/courses/$courseSlug/interventions'
    | '/app/courses/$courseSlug/overview'
    | '/app/courses/$courseSlug/passback'
    | '/app/courses/$courseSlug/roster'
    | '/app/student/assignments/expressions-checkpoint'
    | '/app/student/assignments'
    | '/app/courses/$courseSlug/assignments/$assignmentSlug'
    | '/app/courses/$courseSlug/students/$studentSlug'
    | '/app/courses/$courseSlug/assignments'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/launch'
    | '/pilot-launch'
    | '/product'
    | '/research'
    | '/security'
    | '/thank-you'
    | '/app/activity'
    | '/app/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/app/district/implementation'
    | '/app/district/overview'
    | '/app/leader/interventions'
    | '/app/leader/overview'
    | '/app/leader/standards'
    | '/app/student/feedback'
    | '/app/student/home'
    | '/app/student/progress'
    | '/app/courses/$courseSlug/gradebook'
    | '/app/courses/$courseSlug/insights'
    | '/app/courses/$courseSlug/interventions'
    | '/app/courses/$courseSlug/overview'
    | '/app/courses/$courseSlug/passback'
    | '/app/courses/$courseSlug/roster'
    | '/app/student/assignments/expressions-checkpoint'
    | '/app/student/assignments/'
    | '/app/courses/$courseSlug/assignments/$assignmentSlug'
    | '/app/courses/$courseSlug/students/$studentSlug'
    | '/app/courses/$courseSlug/assignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LaunchRoute: typeof LaunchRoute
  PilotLaunchRoute: typeof PilotLaunchRoute
  ProductRoute: typeof ProductRoute
  ResearchRoute: typeof ResearchRoute
  SecurityRoute: typeof SecurityRoute
  ThankYouRoute: typeof ThankYouRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot-launch': {
      id: '/pilot-launch'
      path: '/pilot-launch'
      fullPath: '/pilot-launch'
      preLoaderRoute: typeof PilotLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/progress': {
      id: '/app/student/progress'
      path: '/student/progress'
      fullPath: '/app/student/progress'
      preLoaderRoute: typeof AppStudentProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/home': {
      id: '/app/student/home'
      path: '/student/home'
      fullPath: '/app/student/home'
      preLoaderRoute: typeof AppStudentHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/feedback': {
      id: '/app/student/feedback'
      path: '/student/feedback'
      fullPath: '/app/student/feedback'
      preLoaderRoute: typeof AppStudentFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leader/standards': {
      id: '/app/leader/standards'
      path: '/leader/standards'
      fullPath: '/app/leader/standards'
      preLoaderRoute: typeof AppLeaderStandardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leader/overview': {
      id: '/app/leader/overview'
      path: '/leader/overview'
      fullPath: '/app/leader/overview'
      preLoaderRoute: typeof AppLeaderOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leader/interventions': {
      id: '/app/leader/interventions'
      path: '/leader/interventions'
      fullPath: '/app/leader/interventions'
      preLoaderRoute: typeof AppLeaderInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/district/overview': {
      id: '/app/district/overview'
      path: '/district/overview'
      fullPath: '/app/district/overview'
      preLoaderRoute: typeof AppDistrictOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/district/implementation': {
      id: '/app/district/implementation'
      path: '/district/implementation'
      fullPath: '/app/district/implementation'
      preLoaderRoute: typeof AppDistrictImplementationRouteImport
      parentRoute: typeof AppRoute
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/student/assignments/': {
      id: '/app/student/assignments/'
      path: '/student/assignments'
      fullPath: '/app/student/assignments/'
      preLoaderRoute: typeof AppStudentAssignmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/student/assignments/expressions-checkpoint': {
      id: '/app/student/assignments/expressions-checkpoint'
      path: '/student/assignments/expressions-checkpoint'
      fullPath: '/app/student/assignments/expressions-checkpoint'
      preLoaderRoute: typeof AppStudentAssignmentsExpressionsCheckpointRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/roster': {
      id: '/app/courses/$courseSlug/roster'
      path: '/courses/$courseSlug/roster'
      fullPath: '/app/courses/$courseSlug/roster'
      preLoaderRoute: typeof AppCoursesCourseSlugRosterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/passback': {
      id: '/app/courses/$courseSlug/passback'
      path: '/courses/$courseSlug/passback'
      fullPath: '/app/courses/$courseSlug/passback'
      preLoaderRoute: typeof AppCoursesCourseSlugPassbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/overview': {
      id: '/app/courses/$courseSlug/overview'
      path: '/courses/$courseSlug/overview'
      fullPath: '/app/courses/$courseSlug/overview'
      preLoaderRoute: typeof AppCoursesCourseSlugOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/interventions': {
      id: '/app/courses/$courseSlug/interventions'
      path: '/courses/$courseSlug/interventions'
      fullPath: '/app/courses/$courseSlug/interventions'
      preLoaderRoute: typeof AppCoursesCourseSlugInterventionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/insights': {
      id: '/app/courses/$courseSlug/insights'
      path: '/courses/$courseSlug/insights'
      fullPath: '/app/courses/$courseSlug/insights'
      preLoaderRoute: typeof AppCoursesCourseSlugInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/gradebook': {
      id: '/app/courses/$courseSlug/gradebook'
      path: '/courses/$courseSlug/gradebook'
      fullPath: '/app/courses/$courseSlug/gradebook'
      preLoaderRoute: typeof AppCoursesCourseSlugGradebookRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/assignments/': {
      id: '/app/courses/$courseSlug/assignments/'
      path: '/courses/$courseSlug/assignments'
      fullPath: '/app/courses/$courseSlug/assignments/'
      preLoaderRoute: typeof AppCoursesCourseSlugAssignmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/students/$studentSlug': {
      id: '/app/courses/$courseSlug/students/$studentSlug'
      path: '/courses/$courseSlug/students/$studentSlug'
      fullPath: '/app/courses/$courseSlug/students/$studentSlug'
      preLoaderRoute: typeof AppCoursesCourseSlugStudentsStudentSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/courses/$courseSlug/assignments/$assignmentSlug': {
      id: '/app/courses/$courseSlug/assignments/$assignmentSlug'
      path: '/courses/$courseSlug/assignments/$assignmentSlug'
      fullPath: '/app/courses/$courseSlug/assignments/$assignmentSlug'
      preLoaderRoute: typeof AppCoursesCourseSlugAssignmentsAssignmentSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDistrictImplementationRoute: typeof AppDistrictImplementationRoute
  AppDistrictOverviewRoute: typeof AppDistrictOverviewRoute
  AppLeaderInterventionsRoute: typeof AppLeaderInterventionsRoute
  AppLeaderOverviewRoute: typeof AppLeaderOverviewRoute
  AppLeaderStandardsRoute: typeof AppLeaderStandardsRoute
  AppStudentFeedbackRoute: typeof AppStudentFeedbackRoute
  AppStudentHomeRoute: typeof AppStudentHomeRoute
  AppStudentProgressRoute: typeof AppStudentProgressRoute
  AppCoursesCourseSlugGradebookRoute: typeof AppCoursesCourseSlugGradebookRoute
  AppCoursesCourseSlugInsightsRoute: typeof AppCoursesCourseSlugInsightsRoute
  AppCoursesCourseSlugInterventionsRoute: typeof AppCoursesCourseSlugInterventionsRoute
  AppCoursesCourseSlugOverviewRoute: typeof AppCoursesCourseSlugOverviewRoute
  AppCoursesCourseSlugPassbackRoute: typeof AppCoursesCourseSlugPassbackRoute
  AppCoursesCourseSlugRosterRoute: typeof AppCoursesCourseSlugRosterRoute
  AppStudentAssignmentsExpressionsCheckpointRoute: typeof AppStudentAssignmentsExpressionsCheckpointRoute
  AppStudentAssignmentsIndexRoute: typeof AppStudentAssignmentsIndexRoute
  AppCoursesCourseSlugAssignmentsAssignmentSlugRoute: typeof AppCoursesCourseSlugAssignmentsAssignmentSlugRoute
  AppCoursesCourseSlugStudentsStudentSlugRoute: typeof AppCoursesCourseSlugStudentsStudentSlugRoute
  AppCoursesCourseSlugAssignmentsIndexRoute: typeof AppCoursesCourseSlugAssignmentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppIndexRoute: AppIndexRoute,
  AppDistrictImplementationRoute: AppDistrictImplementationRoute,
  AppDistrictOverviewRoute: AppDistrictOverviewRoute,
  AppLeaderInterventionsRoute: AppLeaderInterventionsRoute,
  AppLeaderOverviewRoute: AppLeaderOverviewRoute,
  AppLeaderStandardsRoute: AppLeaderStandardsRoute,
  AppStudentFeedbackRoute: AppStudentFeedbackRoute,
  AppStudentHomeRoute: AppStudentHomeRoute,
  AppStudentProgressRoute: AppStudentProgressRoute,
  AppCoursesCourseSlugGradebookRoute: AppCoursesCourseSlugGradebookRoute,
  AppCoursesCourseSlugInsightsRoute: AppCoursesCourseSlugInsightsRoute,
  AppCoursesCourseSlugInterventionsRoute:
    AppCoursesCourseSlugInterventionsRoute,
  AppCoursesCourseSlugOverviewRoute: AppCoursesCourseSlugOverviewRoute,
  AppCoursesCourseSlugPassbackRoute: AppCoursesCourseSlugPassbackRoute,
  AppCoursesCourseSlugRosterRoute: AppCoursesCourseSlugRosterRoute,
  AppStudentAssignmentsExpressionsCheckpointRoute:
    AppStudentAssignmentsExpressionsCheckpointRoute,
  AppStudentAssignmentsIndexRoute: AppStudentAssignmentsIndexRoute,
  AppCoursesCourseSlugAssignmentsAssignmentSlugRoute:
    AppCoursesCourseSlugAssignmentsAssignmentSlugRoute,
  AppCoursesCourseSlugStudentsStudentSlugRoute:
    AppCoursesCourseSlugStudentsStudentSlugRoute,
  AppCoursesCourseSlugAssignmentsIndexRoute:
    AppCoursesCourseSlugAssignmentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LaunchRoute: LaunchRoute,
  PilotLaunchRoute: PilotLaunchRoute,
  ProductRoute: ProductRoute,
  ResearchRoute: ResearchRoute,
  SecurityRoute: SecurityRoute,
  ThankYouRoute: ThankYouRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
